### PR TITLE
Extendable node types, Updated JSEP support

### PR DESCRIPTION
**Pull request by 6utt3rfly**
From #61 
This looks like a big PR (so sorry!) ... but instead of squashing my commits, I thought it might be useful to see the history of commits to get here for reviewing.

This PR makes a few major changes:
1. Changes from exported functions to an exported default class (but keeping the same properties as before). This change allows state to be maintained within a class instance while parsing, so that the Context doesn't need to be passed to each evaluator method, and so that `isAsync` can be checked at runtime rather than having to duplicate all evaluator code
2. Merged sync/async methods into one. Now they go through a `evalSyncAsync` method which takes a callback argument so that it can either chain promises (async), or it can simply return the value (sync). It makes the code slightly less readable in a few places where it looks like old-school nested callbacks, but I thought the tradeoff of less code to duplicate/maintain (and smaller build size) was worth it.
3. Added support for new node types from JSEP's new plugin package system: arrow function, assignment/update, `new`, objects, spread, (tagged)template literals.
4. Added support for adding/modifying the node parsers by changing from a `switch`-statement to a map of node types to function  handlers.

There are a few other changes too:
- LogicalExpression/BinaryExpression are treated identically now (jsep recently dropped the LogicalExpression node type)
- evaluating throws on invalid functions instead of returning undefined
- updated/more types

I'm happy to take any feedback and hope this can be used!

_Note: jsep is not yet released, so I had to manually build it and copy to the node_modules folder to develop and test_

### CODE REVIEW

**Comment by 6utt3rfly** [comment]
JSEP 1.0.1 and the related plugins are released, so I've marked it as ready for review now :-)

**Comment by mahish** [comment]
Hi, im doing research on expression evaluator packages. I like this one most:) And Im happy to see this PR as the missing support for `new Date()` objects prevents me from actually using the package. Any idea whether can this be merged and released? Thanks.

**Comment by bman654** [comment]
I'd also love to see this merged/published.

**Comment by mahish** [comment]
@bman654 I realized there is the fork https://github.com/6utt3rfly/jse-eval/

**Comment by donmccurdy** [comment]
Sorry for the delay in responding here. I will be archiving this repository and deprecating the npm package. See: https://github.com/donmccurdy/expression-eval/commit/0a8d3f3038556244f5163d61afcf53950bf6e71a.

**Pull request closed without merging**
